"""Add enhanced table metadata fields

Revision ID: 0145c7e28cc9
Revises: ac4d3d3c8bd0
Create Date: 2025-09-10 15:33:19.526320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0145c7e28cc9'
down_revision: Union[str, Sequence[str], None] = 'ac4d3d3c8bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_metrics', sa.Column('table_type', sa.String(length=50), nullable=True))
    op.add_column('table_metrics', sa.Column('storage_format', sa.String(length=50), nullable=True))
    op.add_column('table_metrics', sa.Column('input_format', sa.String(length=200), nullable=True))
    op.add_column('table_metrics', sa.Column('output_format', sa.String(length=200), nullable=True))
    op.add_column('table_metrics', sa.Column('serde_lib', sa.String(length=200), nullable=True))
    op.add_column('table_metrics', sa.Column('table_owner', sa.String(length=100), nullable=True))
    op.add_column('table_metrics', sa.Column('table_create_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('table_metrics', sa.Column('partition_columns', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_metrics', 'partition_columns')
    op.drop_column('table_metrics', 'table_create_time')
    op.drop_column('table_metrics', 'table_owner')
    op.drop_column('table_metrics', 'serde_lib')
    op.drop_column('table_metrics', 'output_format')
    op.drop_column('table_metrics', 'input_format')
    op.drop_column('table_metrics', 'storage_format')
    op.drop_column('table_metrics', 'table_type')
    # ### end Alembic commands ###
