"""add_cold_data_fields_to_table_metric

Revision ID: 181b32d53423
Revises: e7caf052f4be
Create Date: 2025-09-17 15:47:50.728164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '181b32d53423'
down_revision: Union[str, Sequence[str], None] = 'e7caf052f4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_metrics', sa.Column('last_access_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('table_metrics', sa.Column('days_since_last_access', sa.Integer(), nullable=True))
    op.add_column('table_metrics', sa.Column('is_cold_data', sa.Integer(), nullable=True, default=0))
    op.add_column('table_metrics', sa.Column('archive_status', sa.String(length=50), nullable=True, default='active'))
    op.add_column('table_metrics', sa.Column('archive_location', sa.String(length=1000), nullable=True))
    op.add_column('table_metrics', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_table_metrics_cdt_id', table_name='table_metrics')
    op.drop_index('ix_table_metrics_cdt_scan_time', table_name='table_metrics')
    op.create_index(op.f('ix_table_metrics_archive_status'), 'table_metrics', ['archive_status'], unique=False)
    op.create_index(op.f('ix_table_metrics_archived_at'), 'table_metrics', ['archived_at'], unique=False)
    op.create_index(op.f('ix_table_metrics_last_access_time'), 'table_metrics', ['last_access_time'], unique=False)
    # Skip JSON type change for SQLite compatibility
    # op.alter_column('task_logs', 'details',
    #           existing_type=sa.TEXT(),
    #           type_=sa.JSON(),
    #           existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip JSON type change for SQLite compatibility
    # op.alter_column('task_logs', 'details',
    #           existing_type=sa.JSON(),
    #           type_=sa.TEXT(),
    #           existing_nullable=True)
    op.drop_index(op.f('ix_table_metrics_last_access_time'), table_name='table_metrics')
    op.drop_index(op.f('ix_table_metrics_archived_at'), table_name='table_metrics')
    op.drop_index(op.f('ix_table_metrics_archive_status'), table_name='table_metrics')
    op.create_index('ix_table_metrics_cdt_scan_time', 'table_metrics', ['cluster_id', 'database_name', 'table_name', 'scan_time'], unique=False)
    op.create_index('ix_table_metrics_cdt_id', 'table_metrics', ['cluster_id', 'database_name', 'table_name', 'id'], unique=False)
    op.drop_column('table_metrics', 'archived_at')
    op.drop_column('table_metrics', 'archive_location')
    op.drop_column('table_metrics', 'archive_status')
    op.drop_column('table_metrics', 'is_cold_data')
    op.drop_column('table_metrics', 'days_since_last_access')
    op.drop_column('table_metrics', 'last_access_time')
    # ### end Alembic commands ###
