"""add ldap auth and yarn monitoring fields to cluster

Revision ID: 7f847c6771ed
Revises: 4011786aead6
Create Date: 2025-09-12 18:35:15.442111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f847c6771ed'
down_revision: Union[str, Sequence[str], None] = '4011786aead6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('auth_type', sa.String(length=20), nullable=True))
    op.add_column('clusters', sa.Column('hive_username', sa.String(length=100), nullable=True))
    op.add_column('clusters', sa.Column('hive_password', sa.String(length=500), nullable=True))
    op.add_column('clusters', sa.Column('yarn_resource_manager_url', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_table_metrics_id'), 'table_metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_metrics_id'), table_name='table_metrics')
    op.drop_column('clusters', 'yarn_resource_manager_url')
    op.drop_column('clusters', 'hive_password')
    op.drop_column('clusters', 'hive_username')
    op.drop_column('clusters', 'auth_type')
    # ### end Alembic commands ###
