"""add detailed progress tracking fields to merge_task

Revision ID: e6490a25d646
Revises: 7f847c6771ed
Create Date: 2025-09-12 18:57:12.058988

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6490a25d646"
down_revision: Union[str, Sequence[str], None] = "7f847c6771ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "merge_tasks", sa.Column("execution_phase", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "merge_tasks", sa.Column("progress_percentage", sa.Float(), nullable=True)
    )
    op.add_column(
        "merge_tasks",
        sa.Column("estimated_remaining_time", sa.Integer(), nullable=True),
    )
    op.add_column(
        "merge_tasks", sa.Column("processed_files_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "merge_tasks", sa.Column("total_files_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "merge_tasks",
        sa.Column("yarn_application_id", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "merge_tasks",
        sa.Column("current_operation", sa.String(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("merge_tasks", "current_operation")
    op.drop_column("merge_tasks", "yarn_application_id")
    op.drop_column("merge_tasks", "total_files_count")
    op.drop_column("merge_tasks", "processed_files_count")
    op.drop_column("merge_tasks", "estimated_remaining_time")
    op.drop_column("merge_tasks", "progress_percentage")
    op.drop_column("merge_tasks", "execution_phase")
    # ### end Alembic commands ###
