"""Add cluster status history and enhanced cluster status fields

Revision ID: e7caf052f4be
Revises: a2b3c4d5e6f7
Create Date: 2025-09-17 13:32:24.825599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7caf052f4be'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('health_status', sa.String(length=20), nullable=True))
    op.add_column('clusters', sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True))

    # Create cluster_status_history table (only if it doesn't exist)
    try:
        op.create_table('cluster_status_history',
            sa.Column('id', sa.Integer(), primary_key=True, index=True),
            sa.Column('cluster_id', sa.Integer(), sa.ForeignKey('clusters.id'), nullable=False, index=True),
            sa.Column('from_status', sa.String(length=20), nullable=True),
            sa.Column('to_status', sa.String(length=20), nullable=False),
            sa.Column('reason', sa.String(length=100), nullable=True),
            sa.Column('message', sa.Text(), nullable=True),
            sa.Column('connection_test_result', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        )
    except Exception:
        # Table already exists, skip creation
        pass

    # Set default health_status for existing clusters
    op.execute("UPDATE clusters SET health_status = 'unknown' WHERE health_status IS NULL")

    op.drop_index('ix_table_metrics_cdt_id', table_name='table_metrics')
    op.drop_index('ix_table_metrics_cdt_scan_time', table_name='table_metrics')
    op.alter_column('task_logs', 'details',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_logs', 'details',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('ix_table_metrics_cdt_scan_time', 'table_metrics', ['cluster_id', 'database_name', 'table_name', 'scan_time'], unique=False)
    op.create_index('ix_table_metrics_cdt_id', 'table_metrics', ['cluster_id', 'database_name', 'table_name', 'id'], unique=False)

    # Drop cluster_status_history table
    op.drop_table('cluster_status_history')

    op.drop_column('clusters', 'last_health_check')
    op.drop_column('clusters', 'health_status')
    # ### end Alembic commands ###
