"""add missing merge task fields

Revision ID: f56f0a5dab2f
Revises: 0145c7e28cc9
Create Date: 2025-09-11 10:31:44.856845

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f56f0a5dab2f"
down_revision: Union[str, Sequence[str], None] = "0145c7e28cc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("merge_tasks", sa.Column("progress", sa.Float(), nullable=True))
    op.add_column(
        "merge_tasks", sa.Column("current_phase", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "merge_tasks", sa.Column("table_lock_acquired", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "merge_tasks", sa.Column("lock_holder", sa.String(length=100), nullable=True)
    )
    op.add_column("merge_tasks", sa.Column("strategy_reason", sa.Text(), nullable=True))
    op.add_column(
        "merge_tasks", sa.Column("auto_selected", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "merge_tasks", sa.Column("estimated_duration", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("merge_tasks", "estimated_duration")
    op.drop_column("merge_tasks", "auto_selected")
    op.drop_column("merge_tasks", "strategy_reason")
    op.drop_column("merge_tasks", "lock_holder")
    op.drop_column("merge_tasks", "table_lock_acquired")
    op.drop_column("merge_tasks", "current_phase")
    op.drop_column("merge_tasks", "progress")
    # ### end Alembic commands ###
