name: Automerge labeled PRs

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, ready_for_review]
  check_suite:
    types: [completed]
  status: {}

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read

concurrency:
  group: automerge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  automerge:
    name: Automerge when labeled and checks pass
    runs-on: ubuntu-latest
    steps:
      - name: Run automerge action
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: pull-request-title
          DELETE_BRANCH: true
          MERGE_LABELS: automerge
          # Optional tuning to avoid long waits
          MERGE_RETRIES: 12
          MERGE_RETRY_SLEEP: 10000

