name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend:
    name: Backend · Python tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install backend deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run backend tests (CI)
        working-directory: backend
        run: |
          export DATABASE_URL="sqlite:////tmp/hive_small_file_db.db"
          # Phase-in: expand unit subset and raise coverage gate to 40%
          python -m pytest \
            test_performance_baseline.py \
            test_scanner.py \
            tests/unit/test_engine_factory_extra.py \
            tests/unit/utils/test_encryption.py \
            tests/unit/utils/test_encryption_extra.py \
            tests/unit/services/test_path_resolver.py \
            tests/unit/services/test_websocket_service.py \
            tests/unit/services/test_enhanced_connection_service_helpers.py \
            tests/unit/services/test_cluster_status_service.py \
            tests/unit/services/test_cluster_status_service_metrics.py \
            tests/unit/api/test_websocket_api_unit.py \
            tests/unit/api/test_websocket_api_endpoints.py \
            tests/unit/api/test_main_health.py \
            tests/unit/api/test_errors_api.py \
            tests/unit/engines/test_base_engine_helpers.py \
            tests/unit/monitor/test_mock_hdfs_scanner.py \
            tests/unit/monitor/test_mysql_hive_connector.py \
            tests/unit/utils/test_table_lock_manager.py \
            tests/unit/test_ci_verification.py \
            --cov=app --cov-report=xml:coverage.xml --cov-fail-under=25 -v --tb=short

      - name: Upload backend coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage.xml

  frontend:
    name: Frontend · Build & tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend deps
        working-directory: frontend
        run: |
          npm install --no-audit --no-fund

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Prettier formatting check (if configured)
        working-directory: frontend
        run: |
          # Run only if project defines the script (opt-in)
          if npm run -s lint:format >/dev/null 2>&1; then
            npm run lint:format
          else
            echo "Prettier script not configured; skipping check"
          fi

      - name: Run frontend unit tests
        working-directory: frontend
        run: npm run test:run

  frontend-e2e-smoke:
    name: Frontend · E2E smoke
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        working-directory: frontend
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '0'
        run: |
          npm ci --no-audit --no-fund || npm install --no-audit --no-fund
          npx playwright install --with-deps chromium

      - name: Build frontend (for preview)
        working-directory: frontend
        run: npm run build

      - name: Run smoke E2E (chromium, smoke)
        working-directory: frontend
        env:
          CI: 'true'
        run: |
          npx http-server dist -p 4173 -a 127.0.0.1 >/dev/null 2>&1 &
          sleep 3
          npx playwright test -c playwright.smoke.noserver.config.ts src/test/e2e/smoke.spec.ts --project=chromium --reporter=line || echo "E2E smoke failed (non-blocking)"

  status:
    name: Project status report
    runs-on: ubuntu-latest
    needs: [ backend, frontend, frontend-e2e-smoke ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate status
        run: |
          make status

      - name: Upload status artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: project-status
          path: |
            PROJECT_STATUS.md
            project_status.json
