name: Debug Network (Self-hosted)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  debug:
    runs-on: [self-hosted, staging]
    steps:
      - name: Check container status
        shell: bash
        run: |
          echo "=== 容器运行状态 ==="
          docker ps -a | grep hive-platform

          echo -e "\n=== 端口监听状态 ==="
          netstat -tlnp | grep ":80\|:8000"

          echo -e "\n=== 防火墙状态 ==="
          sudo iptables -L -n | grep -E "(80|8000)"

          echo -e "\n=== 本机访问测试 ==="
          curl -s --connect-timeout 5 http://127.0.0.1:8000/health || echo "本机API访问失败"
          curl -s --connect-timeout 5 http://127.0.0.1/ | head -5 || echo "本机前端访问失败"

          echo -e "\n=== 外网接口绑定检查 ==="
          curl -s --connect-timeout 5 http://0.0.0.0:8000/health || echo "外网API绑定失败"