name: SSH Only Fix

on:
  workflow_dispatch:

jobs:
  ssh-fix:
    runs-on: [self-hosted, staging]
    steps:
      - name: SSH emergency fix
        shell: bash
        run: |
          echo "SSH紧急修复开始..."

          # 重启SSH服务
          sudo systemctl restart ssh 2>/dev/null || sudo systemctl restart sshd 2>/dev/null || true

          # 完全清理防火墙规则
          sudo iptables -F 2>/dev/null || true
          sudo iptables -X 2>/dev/null || true
          sudo iptables -P INPUT ACCEPT 2>/dev/null || true
          sudo iptables -P FORWARD ACCEPT 2>/dev/null || true
          sudo iptables -P OUTPUT ACCEPT 2>/dev/null || true

          # 添加基本规则
          sudo iptables -A INPUT -i lo -j ACCEPT 2>/dev/null || true
          sudo iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT 2>/dev/null || true
          sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT 2>/dev/null || true
          sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT 2>/dev/null || true
          sudo iptables -A INPUT -p tcp --dport 8000 -j ACCEPT 2>/dev/null || true

          echo "SSH修复完成，请尝试重新连接"