name: Weekly Status Report

on:
  schedule:
    - cron: '0 2 * * 1' # Every Monday at 02:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  weekly-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate project status
        run: |
          python3 scripts/generate_project_status.py

      - name: Upload status artifacts
        uses: actions/upload-artifact@v4
        with:
          name: weekly-project-status
          path: |
            PROJECT_STATUS.md
            project_status.json

